services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.docker
    environment:
      NODE_ENV: docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Host 5433 → Container 5432

  redis:
    image: redis:7
    container_name: redis
    ports:
      # REDIS_PORT must be set in .env
      # not the one used for backend service!!
      # because it has to be read before backend starts
      - "3002:${REDIS_PORT}"

  backend:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    environment:
      NODE_ENV: docker
    ports:
      - "3000:3000"
    command: npm start

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "3003:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  seed:
    build: .
    command: node scripts/seeder.js
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      NODE_ENV: docker

  debug:
    build: .
    command: node scripts/debug.js
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      NODE_ENV: docker


volumes:
  pgdata:
