global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets:
          - 'backend:4000'
          - 'weather:4002'
          - 'subscription:4003'