name: End to End Tests

on: [push, pull_request]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker compose version

      - name: Start database for E2E
        run: |
          docker compose -f docker-compose.test.yml up -d db-test
          echo "Waiting for container to start..."
          sleep 5
          # Check if container is running
          if docker ps | grep -q db-test; then
            echo "db-test container is running"
          else
            echo "ERROR: db-test container is not running"
            docker compose -f docker-compose.test.yml ps
            docker compose -f docker-compose.test.yml logs db-test
            exit 1
          fi
          # Wait for PostgreSQL to be ready with a timeout (e.g., 60 seconds)
          timeout 60 bash -c "until docker compose -f docker-compose.test.yml exec -T db-test pg_isready -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done"
          if [ $? -eq 0 ]; then
            echo "PostgreSQL is ready"
          else
            echo "ERROR: Timeout waiting for PostgreSQL"
            docker compose -f docker-compose.test.yml logs db-test
            exit 1
          fi
        env:
          DATABASE_URL: postgres://postgres:alwayssunny@db-test:5432/weather_db_test

      - name: Run E2E tests
        run: npm run test:e2e:docker
        env:
          DATABASE_URL: postgres://postgres:alwayssunny@db-test:5432/weather_db_test

      - name: Debug logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.test.yml logs db-test
          docker compose -f docker-compose.test.yml logs backend-test
          docker compose -f docker-compose.test.yml logs test-e2e

      - name: Cleanup Docker Compose
        if: always()
        run: docker compose -f docker-compose.test.yml down -v 